### ISSUE TITLE
Recipe field inside Matrix block.

### ISSUE THREAD

**Issue by keyname** [nystudio107/craft3-recipe#63]
When I place the Recipe field in a Matrix block, I get an error where the API cannot fetch the data or see that ingredients have been added.

The message shown is "Please provide some ingredients first."... no matter how many ingredients I add.

(I've confirmed that the API can fetch the same ingredient data when not in a Matrix block.)

**Comment by khalwat** [comment]
This has been addressed. Try it out and let me know if it fixes your issue. Thx @bencroker 

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop as 1.4.2",
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop-v4 as 4.0.5",
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Updated the docs to descript how to do Multi-Component recipes:

https://nystudio107.com/docs/recipe/#multi-component-recipes

Released as:

Craft 3: Version 1.4.2 -> https://github.com/nystudio107/craft-recipe/releases/tag/1.4.2

Craft 3: Version 4.0.5 -> https://github.com/nystudio107/craft-recipe/releases/tag/4.0.5

**Comment by keyname** [comment]
Hi Andrew,

This does not fix the problem.
This new version does not seam to pull any data for the field, no matter
where it is.
(I've also done a fresh install of v4 to ensure it wasn't my previous
build.)

Still no luck.
-
Dan

**Comment by bencroker** [comment]
@keyname can you please provide some more details? What happens when you click the “Fetch Nutritional Information” button? And what do you see in the response of the network request in the browser's console tools?

**Comment by bencroker** [comment]
Fixed and tested in https://github.com/nystudio107/craft-recipe/pull/65.

**Comment by khalwat** [comment]
@keyname if you could test this out please...

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop as 1.4.3",
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-recipe": "dev-develop-v4 as 4.0.6",
```
Then do a `composer clear-cache && composer update`

**Comment by keyname** [comment]
Success!

Working great now.  : )



Thanks.
-
Dan

**Comment by khalwat** [comment]
Released as:

Craft 3: Version 1.4.3 -> https://github.com/nystudio107/craft-recipe/releases/tag/1.4.3

Craft 4: Version 4.0.6 -> https://github.com/nystudio107/craft-recipe/releases/tag/4.0.6
